name: "Auto Merge EIP"
description: "A bot that lints EIP edits, finds common errors, and can auto-merge"
inputs:
  GITHUB-TOKEN:
    description: |-
      The Github token to be used. This is optional because if it's not provided the bot will use a token from a brand new account not associated with any repositories and the key is gone
    required: false
  PR_NUMBER:
    description: The Pull Request number
    required: false
  CORE_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for core eip changes
    required: true
  ERC_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for ERC type changes
    required: true
  NETWORKING_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for NETWORKING type changes
    required: true
  INTERFACE_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for INTERFACE type changes
    required: true
  META_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for META type changes
    required: true
  INFORMATIONAL_EDITORS:
    description: a list of editors in the following format "@github_username,@..." to be mentioned for INFORMATIONAL type changes
    required: true
  MAINTAINERS:
    required: true
    description: a list of users or users or gorups in the following format "@github_username,@..."; these users will be called when the bot experiences an unexpected failure

runs:
  using: composite
  steps:
    - run: node --trace-warnings ${{github.action_path}}/build/src/index.js
      shell: bash
      env:
        ERC_EDITORS: ${{ inputs.ERC_EDITORS }}
        CORE_EDITORS: ${{ inputs.CORE_EDITORS }}
        NETWORKING_EDITORS: ${{ inputs.NETWORKING_EDITORS }}
        INTERFACE_EDITORS: ${{ inputs.INTERFACE_EDITORS }}
        META_EDITORS: ${{ inputs.META_EDITORS }}
        INFORMATIONAL_EDITORS: ${{ inputs.INFORMATIONAL_EDITORS }}
        GITHUB_TOKEN: ${{ inputs.GITHUB-TOKEN }}
        MAINTAINERS: ${{ inputs.MAINTAINERS }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
        NODE_ENV: production

